version: "2"
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - godot
    - godox
    - ireturn
    - lll
    - maintidx
    - nilnil
    - nlreturn
    - paralleltest
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
  settings:
    dupl:
      threshold: 600
    gocritic:
      disabled-checks:
        - ifElseChain
    mnd:
      ignored-files:
        - examples/.*
      ignored-functions:
        - context.WithTimeout
    nestif:
      min-complexity: 9
    revive:
      rules:
        - name: blank-imports
          disabled: true
    wsl:
      strict-append: false
      allow-assign-and-call: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - perfsprint
        path: _test\.go
      - path: (.+)\.go$
        text: if statements should only be cuddled with assignments
      - path: (.+)\.go$
        text: if statements should only be cuddled with assignments used in the if statement itself
      - path: (.+)\.go$
        text: assignments should only be cuddled with other assignments
      - path: (.+)\.go$
        text: declarations should never be cuddled
    paths:
      - ent
      - apis
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - ent
      - apis
      - third_party$
      - builtin$
      - examples$
