version: "0.2"
ignorePaths:
  - go.sum
  - go.mod
dictionaryDefinitions: []
dictionaries: []
words:
  - anyo
  - apierrors
  - apiserver
  - APIURL
  - asasalint
  - asciicheck
  - Balancable
  - bidichk
  - bodyclose
  - bootkit
  - bufbuild
  - canonicalheader
  - containedctx
  - contextcheck
  - copyloopvar
  - covermode
  - coverprofile
  - cyclop
  - davecgh
  - decorder
  - depguard
  - Detailf
  - difflib
  - dogsled
  - duckdb
  - dupl
  - dupword
  - durationcheck
  - dylib
  - entgo
  - err113
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - execinquery
  - exhaustive
  - exhaustruct
  - exportloopref
  - fatcontext
  - forbidigo
  - forcetypeassert
  - funlen
  - gci
  - ginkgolinter
  - GOCACHE
  - gocheckcompilerdirectives
  - gochecknoglobals
  - gochecknoinits
  - gochecksumtype
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godot
  - godox
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - golangci
  - golangci-lint
  - gomnd
  - GOMODCACHE
  - gomoddirectives
  - gomodguard
  - googleapis
  - gopkg
  - goprintffuncname
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - gqlerror
  - gqlgen
  - grouper
  - grpcpkg
  - iface
  - importas
  - inamedparam
  - ineffassign
  - interfacebloat
  - intrange
  - ireturn
  - jsonfmt
  - jsonschema
  - jwtclaim
  - labstack
  - lll
  - loggercheck
  - maintidx
  - makezero
  - mapstructure
  - mirror
  - misspell
  - mitchellh
  - mnd
  - musttag
  - nakedret
  - nekomeowww
  - nestif
  - nilerr
  - nilnil
  - nlreturn
  - noctx
  - nolint
  - nolintlint
  - nonamedreturns
  - nosprintfhostport
  - openaiapiv1
  - openapi
  - openapiv2
  - openapiv3
  - paralleltest
  - perfsprint
  - pg_isready
  - pmezard
  - prealloc
  - predeclared
  - Probs
  - promlinter
  - Protobuf
  - protocolbuffers
  - protogetter
  - protoiface
  - protovalidate
  - reassign
  - recvcheck
  - rediskeys
  - revive
  - rowserrcheck
  - Rueidis
  - samber
  - santhosh-tekuri
  - sashabaranov
  - sloglint
  - Sortby
  - spancheck
  - sqlclosecheck
  - staticcheck
  - stretchr
  - stylecheck
  - tagalign
  - tagliatelle
  - tenv
  - testableexamples
  - testifylint
  - testpackage
  - thelper
  - timestamppb
  - tparallel
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - varnamelen
  - vektah
  - wastedassign
  - wellknowntypes
  - whitespace
  - wrapcheck
  - wsl
  - zerologlint
ignoreWords: []
import:
  - "@cspell/dict-golang"
